services:
  
  php:
    build: ./docker/php
    container_name: testQI_php
    volumes:
      - ./app:/var/www/html
 
  nginx:
    image: nginx:alpine
    container_name: testQI_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
